#! /bin/bash 
IS_OPEN=$(pgrep -x spotify);
if [[ -n $IS_OPEN ]]
then
  echo '| '$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:"org.mpris.MediaPlayer2.Player" string:'Metadata' | grep -Ev "^method" | grep -Eo '("(.*)")|(\b[0-9][a-zA-Z0-9.]*\b)' | sed -E '2~2 a|' | tr -d '\n' | sed -E 's/\|/\n/g;s/(xesam:)|(mpris:)//' | sed -E 's/^"//;s/"$//;s/"+/|/;s/ +/ /g' | grep -Ew 'title|artist' | sort | cut -f2 -d'|' | sed '/^[[:space:]]*$/d;s/^[[:space:]]*//' | paste -s -d'|')' ';
fi
