#! /bin/bash 
POWER="$(upower -i /org/freedesktop/UPower/devices/battery_hidpp_battery_0 | grep 'percentage' | awk '{print $2}')";
LOW="10%";
MID="30%";
HIGH="60%";
FULL="90%";

if [[ ! $POWER > $LOW ]]; then
  echo "     ";
elif [[ ! $POWER < $LOW ]] && [[ ! $POWER > $MID ]]; then
  echo "     ";
elif [[ ! $POWER < $MID ]] && [[ ! $POWER > $HIGH ]]; then
  echo "     ";
elif [[ ! $POWER < $HIGH ]] && [[ ! $POWER > $FULL ]]; then
  echo "     ";
else
  echo "     ";
fi

